---
title: "Data_prep"
output: html_document
date: "2026-06-19"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

library(dplyr)
library(tidyverse)

```{r}
#Đọc dữ liệu
credit_clean <- read.csv("UCI_Credit_Card.csv")

head(credit_clean)
dim(credit_clean)
str(credit_clean)
```

```{r}
#Kiểm tra những dữ liệu còn thiếu
colSums(is.na(credit_clean))
#Tổng số những số liệu còn thiếu (Nếu có)
sum(is.na(credit_clean))
```

```{r}
#kiểm tra dữ liệu trùng lăp
sum(duplicated(credit_clean))
credit_clean <- credit_clean[!duplicated(credit_clean), ]
```

```{r}
#Chuyển các biến phân loại sang factor
# Xử lý giá trị bất thường trước khi chuyển factor
# EDUCATION: 0, 5, 6 -> Others (4)
credit_clean$EDUCATION[credit_clean$EDUCATION %in% c(0, 5, 6)] <- 4
# MARRIAGE: 0 -> Others (3)
credit_clean$MARRIAGE[credit_clean$MARRIAGE == 0] <- 3

# Chuyển các biến phân loại sang factor có nhãn
credit_clean$SEX <- factor(
  credit_clean$SEX,
  levels = c(1, 2),
  labels = c("Male", "Female")
)
credit_clean$EDUCATION <- factor(
  credit_clean$EDUCATION,
  levels = c(1, 2, 3, 4),
  labels = c(
    "Graduate School",
    "University",
    "High School",
    "Others"
  )
)
credit_clean$MARRIAGE <- factor(
  credit_clean$MARRIAGE,
  levels = c(1, 2, 3),
  labels = c(
    "Married",
    "Single",
    "Others"
  )
)
credit_clean$default.payment.next.month <- factor(
  credit_clean$default.payment.next.month,
  levels = c(0, 1),
  labels = c("No Default", "Default")
)
str(credit_clean)
```

```{r}
#Dùng list để nhóm dữ liệu thành các phần chức năng
credit_list <- list(
  Customer = credit_clean[, c("ID","LIMIT_BAL","SEX","AGE")],
  Bill = credit_clean[, grep("BILL_AMT", names(credit_clean))],
  Payment = credit_clean[, grep("PAY_AMT", names(credit_clean))]
)
names(credit_list)
```

```{r}
#Dùng matrix dể tính tổng dư nợ của mỗi khách hàng
bill_matrix <- as.matrix(
  credit_clean[, grep("BILL_AMT", names(credit_clean))]
)
credit_clean$total_bill <- rowSums(bill_matrix)
head(credit_clean$total_bill)
```

```{r}
#Lọc ra những khách hàng có dư nợ cao
high_debt <- subset(
  credit_clean,
  total_bill > 500000
)
head(high_debt)
```

```{r}
#Dùng summary để thống kê mô tả dữ liệu
summary(credit_clean)
table(credit_clean$default.payment.next.month)
```



